// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/api_deployment.proto

package github.com.wedo_workflow.wedo.api;

public final class ApiDeployment {
  private ApiDeployment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeploymentCreateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:github.com.wedo_workflow.wedo.api.DeploymentCreateRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code github.com.wedo_workflow.wedo.api.DeploymentCreateRequest}
   */
  public static final class DeploymentCreateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:github.com.wedo_workflow.wedo.api.DeploymentCreateRequest)
      DeploymentCreateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeploymentCreateRequest.newBuilder() to construct.
    private DeploymentCreateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeploymentCreateRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeploymentCreateRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeploymentCreateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return github.com.wedo_workflow.wedo.api.ApiDeployment.internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return github.com.wedo_workflow.wedo.api.ApiDeployment.internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest.class, github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest)) {
        return super.equals(obj);
      }
      github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest other = (github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code github.com.wedo_workflow.wedo.api.DeploymentCreateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:github.com.wedo_workflow.wedo.api.DeploymentCreateRequest)
        github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return github.com.wedo_workflow.wedo.api.ApiDeployment.internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return github.com.wedo_workflow.wedo.api.ApiDeployment.internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest.class, github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest.Builder.class);
      }

      // Construct using github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return github.com.wedo_workflow.wedo.api.ApiDeployment.internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateRequest_descriptor;
      }

      @java.lang.Override
      public github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest getDefaultInstanceForType() {
        return github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest build() {
        github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest buildPartial() {
        github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest result = new github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest) {
          return mergeFrom((github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest other) {
        if (other == github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:github.com.wedo_workflow.wedo.api.DeploymentCreateRequest)
    }

    // @@protoc_insertion_point(class_scope:github.com.wedo_workflow.wedo.api.DeploymentCreateRequest)
    private static final github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest();
    }

    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeploymentCreateRequest>
        PARSER = new com.google.protobuf.AbstractParser<DeploymentCreateRequest>() {
      @java.lang.Override
      public DeploymentCreateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeploymentCreateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeploymentCreateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeploymentCreateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DeploymentCreateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:github.com.wedo_workflow.wedo.api.DeploymentCreateResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code github.com.wedo_workflow.wedo.api.DeploymentCreateResponse}
   */
  public static final class DeploymentCreateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:github.com.wedo_workflow.wedo.api.DeploymentCreateResponse)
      DeploymentCreateResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeploymentCreateResponse.newBuilder() to construct.
    private DeploymentCreateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeploymentCreateResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeploymentCreateResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeploymentCreateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return github.com.wedo_workflow.wedo.api.ApiDeployment.internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return github.com.wedo_workflow.wedo.api.ApiDeployment.internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse.class, github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse)) {
        return super.equals(obj);
      }
      github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse other = (github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code github.com.wedo_workflow.wedo.api.DeploymentCreateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:github.com.wedo_workflow.wedo.api.DeploymentCreateResponse)
        github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return github.com.wedo_workflow.wedo.api.ApiDeployment.internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return github.com.wedo_workflow.wedo.api.ApiDeployment.internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse.class, github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse.Builder.class);
      }

      // Construct using github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return github.com.wedo_workflow.wedo.api.ApiDeployment.internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateResponse_descriptor;
      }

      @java.lang.Override
      public github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse getDefaultInstanceForType() {
        return github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse.getDefaultInstance();
      }

      @java.lang.Override
      public github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse build() {
        github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse buildPartial() {
        github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse result = new github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse) {
          return mergeFrom((github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse other) {
        if (other == github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:github.com.wedo_workflow.wedo.api.DeploymentCreateResponse)
    }

    // @@protoc_insertion_point(class_scope:github.com.wedo_workflow.wedo.api.DeploymentCreateResponse)
    private static final github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse();
    }

    public static github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeploymentCreateResponse>
        PARSER = new com.google.protobuf.AbstractParser<DeploymentCreateResponse>() {
      @java.lang.Override
      public DeploymentCreateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeploymentCreateResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeploymentCreateResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeploymentCreateResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public github.com.wedo_workflow.wedo.api.ApiDeployment.DeploymentCreateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030api/api_deployment.proto\022!github.com.w" +
      "edo_workflow.wedo.api\032\034google/api/annota" +
      "tions.proto\032\037google/protobuf/timestamp.p" +
      "roto\"\031\n\027DeploymentCreateRequest\"\032\n\030Deplo" +
      "ymentCreateResponseB#Z!github.com/wedo-w" +
      "orkflow/wedo/apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateRequest_descriptor,
        new java.lang.String[] { });
    internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_github_com_wedo_workflow_wedo_api_DeploymentCreateResponse_descriptor,
        new java.lang.String[] { });
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
