// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/api.proto

package github.com.wedo_workflow.wedo;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rapi/api.proto\022\035github.com.wedo_workflo" +
      "w.wedo\032\034google/api/annotations.proto\032\037go" +
      "ogle/protobuf/timestamp.proto\032\030api/api_d" +
      "eployment.proto2\275\001\n\026CloudTaskManageServi" +
      "ce\022\242\001\n\020DeploymentCreate\0226.github.com.wed" +
      "o_workflow.wedo.DeploymentCreateRequest\032" +
      "7.github.com.wedo_workflow.wedo.Deployme" +
      "ntCreateResponse\"\035\202\323\344\223\002\027\"\022/deployment/cr" +
      "eate:\001*B\037Z\035github.com/wedo-workflow/wedo" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          github.com.wedo_workflow.wedo.ApiDeployment.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    github.com.wedo_workflow.wedo.ApiDeployment.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
