// Code generated by xsdgen. DO NOT EDIT.

package schema

type Bounds struct {
	X      float64 `xml:"x,attr"`
	Y      float64 `xml:"y,attr"`
	Width  float64 `xml:"width,attr"`
	Height float64 `xml:"height,attr"`
}

type Font struct {
	Name            string  `xml:"name,attr,omitempty"`
	Size            float64 `xml:"size,attr,omitempty"`
	IsBold          bool    `xml:"isBold,attr,omitempty"`
	IsItalic        bool    `xml:"isItalic,attr,omitempty"`
	IsUnderline     bool    `xml:"isUnderline,attr,omitempty"`
	IsStrikeThrough bool    `xml:"isStrikeThrough,attr,omitempty"`
}

type Point struct {
	X float64 `xml:"x,attr"`
	Y float64 `xml:"y,attr"`
}
