// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/api.proto

#include "api/api.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace github {
namespace com {
namespace wedo_workflow {
namespace wedo {
}  // namespace wedo
}  // namespace wedo_workflow
}  // namespace com
}  // namespace github
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_api_2fapi_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_api_2fapi_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_api_2fapi_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_api_2fapi_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_api_2fapi_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rapi/api.proto\022\035github.com.wedo_workflo"
  "w.wedo\032\034google/api/annotations.proto\032\037go"
  "ogle/protobuf/timestamp.proto\032\030api/api_d"
  "eployment.proto2\275\001\n\026CloudTaskManageServi"
  "ce\022\242\001\n\020DeploymentCreate\0226.github.com.wed"
  "o_workflow.wedo.DeploymentCreateRequest\032"
  "7.github.com.wedo_workflow.wedo.Deployme"
  "ntCreateResponse\"\035\202\323\344\223\002\027\"\022/deployment/cr"
  "eate:\001*B\037Z\035github.com/wedo-workflow/wedo"
  "b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_api_2fapi_2eproto_deps[3] = {
  &::descriptor_table_api_2fapi_5fdeployment_2eproto,
  &::descriptor_table_google_2fapi_2fannotations_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_api_2fapi_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_api_2fapi_2eproto = {
  false, false, 368, descriptor_table_protodef_api_2fapi_2eproto, "api/api.proto", 
  &descriptor_table_api_2fapi_2eproto_once, descriptor_table_api_2fapi_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_api_2fapi_2eproto::offsets,
  file_level_metadata_api_2fapi_2eproto, file_level_enum_descriptors_api_2fapi_2eproto, file_level_service_descriptors_api_2fapi_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_api_2fapi_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_api_2fapi_2eproto);
  return descriptor_table_api_2fapi_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_api_2fapi_2eproto(&descriptor_table_api_2fapi_2eproto);
namespace github {
namespace com {
namespace wedo_workflow {
namespace wedo {

// @@protoc_insertion_point(namespace_scope)
}  // namespace wedo
}  // namespace wedo_workflow
}  // namespace com
}  // namespace github
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
