// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/api_deployment.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_api_2fapi_5fdeployment_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_api_2fapi_5fdeployment_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "google/api/annotations.pb.h"
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_api_2fapi_5fdeployment_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_api_2fapi_5fdeployment_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_api_2fapi_5fdeployment_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_api_2fapi_5fdeployment_2eproto_metadata_getter(int index);
namespace github {
namespace com {
namespace wedo_workflow {
namespace wedo {
class DeploymentCreateRequest;
struct DeploymentCreateRequestDefaultTypeInternal;
extern DeploymentCreateRequestDefaultTypeInternal _DeploymentCreateRequest_default_instance_;
class DeploymentCreateResponse;
struct DeploymentCreateResponseDefaultTypeInternal;
extern DeploymentCreateResponseDefaultTypeInternal _DeploymentCreateResponse_default_instance_;
}  // namespace wedo
}  // namespace wedo_workflow
}  // namespace com
}  // namespace github
PROTOBUF_NAMESPACE_OPEN
template<> ::github::com::wedo_workflow::wedo::DeploymentCreateRequest* Arena::CreateMaybeMessage<::github::com::wedo_workflow::wedo::DeploymentCreateRequest>(Arena*);
template<> ::github::com::wedo_workflow::wedo::DeploymentCreateResponse* Arena::CreateMaybeMessage<::github::com::wedo_workflow::wedo::DeploymentCreateResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace github {
namespace com {
namespace wedo_workflow {
namespace wedo {

// ===================================================================

class DeploymentCreateRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:github.com.wedo_workflow.wedo.DeploymentCreateRequest) */ {
 public:
  inline DeploymentCreateRequest() : DeploymentCreateRequest(nullptr) {}
  virtual ~DeploymentCreateRequest();
  explicit constexpr DeploymentCreateRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeploymentCreateRequest(const DeploymentCreateRequest& from);
  DeploymentCreateRequest(DeploymentCreateRequest&& from) noexcept
    : DeploymentCreateRequest() {
    *this = ::std::move(from);
  }

  inline DeploymentCreateRequest& operator=(const DeploymentCreateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeploymentCreateRequest& operator=(DeploymentCreateRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DeploymentCreateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeploymentCreateRequest* internal_default_instance() {
    return reinterpret_cast<const DeploymentCreateRequest*>(
               &_DeploymentCreateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DeploymentCreateRequest& a, DeploymentCreateRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DeploymentCreateRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeploymentCreateRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DeploymentCreateRequest* New() const final {
    return CreateMaybeMessage<DeploymentCreateRequest>(nullptr);
  }

  DeploymentCreateRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DeploymentCreateRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DeploymentCreateRequest& from);
  void MergeFrom(const DeploymentCreateRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeploymentCreateRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "github.com.wedo_workflow.wedo.DeploymentCreateRequest";
  }
  protected:
  explicit DeploymentCreateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_api_2fapi_5fdeployment_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:github.com.wedo_workflow.wedo.DeploymentCreateRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_api_2fapi_5fdeployment_2eproto;
};
// -------------------------------------------------------------------

class DeploymentCreateResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:github.com.wedo_workflow.wedo.DeploymentCreateResponse) */ {
 public:
  inline DeploymentCreateResponse() : DeploymentCreateResponse(nullptr) {}
  virtual ~DeploymentCreateResponse();
  explicit constexpr DeploymentCreateResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeploymentCreateResponse(const DeploymentCreateResponse& from);
  DeploymentCreateResponse(DeploymentCreateResponse&& from) noexcept
    : DeploymentCreateResponse() {
    *this = ::std::move(from);
  }

  inline DeploymentCreateResponse& operator=(const DeploymentCreateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeploymentCreateResponse& operator=(DeploymentCreateResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DeploymentCreateResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeploymentCreateResponse* internal_default_instance() {
    return reinterpret_cast<const DeploymentCreateResponse*>(
               &_DeploymentCreateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DeploymentCreateResponse& a, DeploymentCreateResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(DeploymentCreateResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeploymentCreateResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DeploymentCreateResponse* New() const final {
    return CreateMaybeMessage<DeploymentCreateResponse>(nullptr);
  }

  DeploymentCreateResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DeploymentCreateResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DeploymentCreateResponse& from);
  void MergeFrom(const DeploymentCreateResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeploymentCreateResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "github.com.wedo_workflow.wedo.DeploymentCreateResponse";
  }
  protected:
  explicit DeploymentCreateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_api_2fapi_5fdeployment_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:github.com.wedo_workflow.wedo.DeploymentCreateResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_api_2fapi_5fdeployment_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DeploymentCreateRequest

// -------------------------------------------------------------------

// DeploymentCreateResponse

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace wedo
}  // namespace wedo_workflow
}  // namespace com
}  // namespace github

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_api_2fapi_5fdeployment_2eproto
