// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package wedo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WedoServiceClient is the client API for WedoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WedoServiceClient interface {
	// Creates a deployment.
	DeploymentCreate(ctx context.Context, in *DeploymentCreateRequest, opts ...grpc.CallOption) (*DeploymentCreateResponse, error)
}

type wedoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWedoServiceClient(cc grpc.ClientConnInterface) WedoServiceClient {
	return &wedoServiceClient{cc}
}

func (c *wedoServiceClient) DeploymentCreate(ctx context.Context, in *DeploymentCreateRequest, opts ...grpc.CallOption) (*DeploymentCreateResponse, error) {
	out := new(DeploymentCreateResponse)
	err := c.cc.Invoke(ctx, "/github.com.wedo_workflow.wedo.api.v1.WedoService/DeploymentCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WedoServiceServer is the server API for WedoService service.
// All implementations should embed UnimplementedWedoServiceServer
// for forward compatibility
type WedoServiceServer interface {
	// Creates a deployment.
	DeploymentCreate(context.Context, *DeploymentCreateRequest) (*DeploymentCreateResponse, error)
}

// UnimplementedWedoServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWedoServiceServer struct {
}

func (UnimplementedWedoServiceServer) DeploymentCreate(context.Context, *DeploymentCreateRequest) (*DeploymentCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeploymentCreate not implemented")
}

// UnsafeWedoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WedoServiceServer will
// result in compilation errors.
type UnsafeWedoServiceServer interface {
	mustEmbedUnimplementedWedoServiceServer()
}

func RegisterWedoServiceServer(s grpc.ServiceRegistrar, srv WedoServiceServer) {
	s.RegisterService(&WedoService_ServiceDesc, srv)
}

func _WedoService_DeploymentCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WedoServiceServer).DeploymentCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.wedo_workflow.wedo.api.v1.WedoService/DeploymentCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WedoServiceServer).DeploymentCreate(ctx, req.(*DeploymentCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WedoService_ServiceDesc is the grpc.ServiceDesc for WedoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WedoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.wedo_workflow.wedo.api.v1.WedoService",
	HandlerType: (*WedoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeploymentCreate",
			Handler:    _WedoService_DeploymentCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
